---
# tasks file for rundeck
- name: create rundeck directory
  file:
    path: "{{ rdeckbase }}"
    state: directory

- name: download rundeck
  get_url:
    url: "{{ url }}/{{ rundeck }}"
    dest: "{{ rdeckbase }}/{{ rundeck }}"

- name: start rundeck
  shell: nohup java -Xmx{{ xmx }} -jar {{ rdeckbase }}/{{ rundeck }} < /dev/null &
  args:
    creates: "{{ rdeckbase }}/server/work"
  register: output

- name: show output
  debug:
    var: output
