---
# tasks file for rundeck
- name: create rundeck directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rundeck_rdeckbase }}"
    - "{{ rundeck_rdeckbase }}/etc"
    - "{{ rundeck_rdeckbase }}/var"

- name: download rundeck
  get_url:
    url: "{{ rundeck_download_url }}/{{ rundeck_jar }}"
    dest: "{{ rundeck_rdeckbase }}/{{ rundeck_jar }}"
  register: downloadrundeck
  until: downloadrundeck is succeeded
  retries: 3
  notify:
    - unpack rundeck
    - wait until unpacked

- name: register rundeck to a sysvinit system
  template:
    src: rundeck.j2
    dest: "/etc/init.d/rundeck"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit" or ansible_service_mgr == "upstart"

- name: register rundeck to a systemd system
  template:
    src: rundeck.service.j2
    dest: /etc/systemd/system/rundeck.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemd daemon reload

- name: flush_handlers
  meta: flush_handlers

- name: configure rundeck profile
  template:
    src: profile.j2
    dest: "{{ rundeck_rdeckbase }}/etc/profile"

- name: configure rundeck properties
  lineinfile:
    dest: "{{ rundeck_rdeckbase }}/server/config/rundeck-config.properties"
    line: "{{ item.parameter }} = {{ item.value }}"
    regexp: "^{{ item.parameter }}"
    create: yes
  notify: restart rundeck
  with_items:
    - "{{ rundeck_config }}"
  loop_control:
    label: "{{ item.parameter }}"

- name: configure rundeck framework
  lineinfile:
    dest: "{{ rundeck_rdeckbase }}/etc/framework.properties"
    line: "{{ item.parameter }} = {{ item.value }}"
    regexp: "^{{ item.parameter }}"
    create: yes
  notify: restart rundeck
  with_items:
    - "{{ rundeck_framework }}"
  loop_control:
    label: "{{ item.parameter }}"

- name: configure rundeck policy
  template:
    src: admin.aclpolicy.j2
    dest: "{{ rundeck_rdeckbase }}/etc/admin.aclpolicy"
  notify: restart rundeck

- name: start rundeck
  service:
    name: rundeck
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
