---
# tasks file for rundeck
- name: create rundeck directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rundeck_rdeckbase }}"

- name: download rundeck
  get_url:
    url: "{{ rundeck_download_url }}/{{ rundeck_jar }}"
    dest: "{{ rundeck_rdeckbase }}/{{ rundeck_jar }}"
  notify:
    - start rundeck
    - wait until unpacked
    - stop rundeck

- name: register rundeck to a sysvinit system
  template:
    src: templates/rundeck.j2
    dest: "/etc/init.d/rundeck"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit" or ansible_service_mgr == "upstart"

- name: register rundeck to a systemd system
  template:
    src: templates/rundeck.service.j2
    dest: /etc/systemd/system/rundeck.service
  when:
    - ansible_service_mgr == "systemd"

- name: flush handlers
  meta: flush_handlers

- name: configure rundeck
  lineinfile:
    dest: "{{ rundeck_rdeckbase }}/etc/framework.properties"
    line: "framework.rundeck.url={{ rundeck_url }}"
  notify: restart rundeck

- name: start rundeck
  service:
    name: rundeckd
    state: started
    enabled: true
