---
# tasks file for rundeck
- name: create rundeck directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ rundeck_rdeckbase }}"

- name: download rundeck
  get_url:
    url: "{{ rundeck_download_url }}/{{ rundeck_jar }}"
    dest: "{{ rundeck_rdeckbase }}/{{ rundeck_jar }}"
  notify:
    - unpack rundeck

- name: register rundeck to a sysvinit system
  template:
    src: templates/rundeck.j2
    dest: "/etc/init.d/rundeck"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit" or ansible_service_mgr == "upstart"

- name: register rundeck to a systemd system
  template:
    src: templates/rundeck.service.j2
    dest: /etc/systemd/system/rundeck.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemd daemon reload

- name: flush handlers
  meta: flush_handlers

- name: configure rundeck framework
  lineinfile:
    dest: "{{ rundeck_rdeckbase }}/etc/framework.properties"
    line: "framework.server.url = {{ rundeck_url }}"
    regexp: "^framework.server.url"
  notify: restart rundeck

- name: configure rundeck profile
  lineinfile:
    dest: "{{ rundeck_rdeckbase }}/etc/profile"
    line: 'export RDECK_JVM="$RDECK_JVM -Xmx{{ rundeck_xmx }}m -Xms{{ rundeck_xms }}m -XX:MaxMetaspaceSize={{ rundeck_maxmetaspacesize }}m -server"'
    regexp: '^export RDECK_JVM='
  notify: restart rundeck

- name: start rundeck
  service:
    name: rundeck
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
