---
# handlers file for rundeck
- name: start rundeck
  shell: nohup java -Xmx{{ rundeck_xmx }} -jar {{ rundeck_rdeckbase }}/{{ rundeck_jar }} < /dev/null &

- name: wait until unpacked
  wait_for:
    path: "{{ rundeck_rdeckbase }}/etc/framework.properties"

- name: stop rundeck
  command: pkill java
