---
# handlers file for rundeck
- name: unpack rundeck
  command: "java -jar {{ rundeck_rdeckbase }}/rundeck-{{ rundeck_version }}-{{ rundeck_release_date }}.war"
  args:
    chdir: "{{ rundeck_rdeckbase }}"

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  notify:
    - restart rundeck

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
