---
# handlers file for rundeck
- name: start rundeck
  service:
    name: rundeck
    state: started

- name: wait until unpacked
  wait_for:
    path: "{{ rundeck_rdeckbase }}/etc/framework.properties"

- name: stop rundeck
  service:
    name: rundeck
    state: stopped

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
