---
# handlers file for rundeck
- name: start rundeck
  service:
    name: rundeck
    state: started

- name: unpack rundeck
  command: java -jar --installonly {{ rundeck_rdeckbase }}/rundeck-launcher-{{ rundeck_version }}.jar

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
