---
# handlers file for rundeck
- name: wait until unpacked
  wait_for:
    path: "{{ rundeck_rdeckbase }}/etc/framework.properties"
  notify: stop rundeck

- name: start rundeck
  service:
    name: rundeck
    state: started

- name: stop rundeck
  service:
    name: rundeck
    state: stopped

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
