---
# handlers file for rundeck
- name: unpack rundeck
  command: java -jar {{ rundeck_rdeckbase }}/rundeck-launcher-{{ rundeck_version }}.jar
  args:
    chdir: "{{ rundeck_rdeckbase }}"
  async: 60
  poll: 0

- name: wait until unpacked
  wait_for:
    path: "{{ rundeck_rdeckbase }}/server"
  notify:
    - stop rundeck

- name: start rundeck
  service:
    name: rundeck
    state: started
  when:
    - ansible_virtualization_type != "docker"

- name: stop rundeck
  service:
    name: rundeck
    state: stopped
  when:
    - ansible_virtualization_type != "docker"

- name: restart rundeck
  service:
    name: rundeck
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemd daemon reload
  systemd:
    daemon_reload: yes
