---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: rundeck-alpine-3.6
    image: alpine:3.6
  - name: rundeck-alpine-3.7
    image: alpine:3.7
  - name: rundeck-centos-6
    image: centos:6
  - name: rundeck-centos-7
    image: centos:7
  - name: rundeck-debian-buster
    image: debian:buster
  - name: rundeck-fedora-26
    image: fedora:26
  - name: rundeck-fedora-27
    image: fedora:27
  - name: rundeck-ubuntu-zesty
    image: ubuntu:zesty
  - name: rundeck-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: goss
  lint:
    name: 'None'
