---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
platforms:
  # 16.04 LTS
  - name: rundeck-ubuntu-xenial
    image: ubuntu:xenial
  # 17.04
  - name: rundeck-ubuntu-artful
    image: ubuntu:artful
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: ubuntu
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - check
    - side_effect
    - verify
    - destroy
verifier:
  name: goss
  lint:
    name: 'flake8'
