---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes
  strategy: free

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.java
      java_version: 8
    - role: ansible-role-rundeck
